package manifest

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jeanmolossi/vibe-and-kalika-code/internal/security"
)

func Validate(packageRoot, projectRoot string, m *Manifest) ([]string, error) {
	var issues []string
	if m.Name == "" {
		issues = append(issues, "name is required")
	}
	if m.Version == "" {
		issues = append(issues, "version is required")
	}
	if m.Description == "" {
		issues = append(issues, "description is required")
	}
	if len(m.Targets) == 0 {
		issues = append(issues, "targets are required")
	}
	declared := map[string]struct{}{}
	for _, target := range m.Targets {
		if !isSupportedTarget(target) {
			issues = append(issues, fmt.Sprintf("unsupported target %q", target))
		}
		declared[target] = struct{}{}
	}
	if err := security.RejectEscapingSymlinks(packageRoot); err != nil {
		issues = append(issues, err.Error())
	}
	duplicates := map[string]string{}
	for _, agent := range m.Agents {
		if agent.Name == "" {
			issues = append(issues, "agent name is required")
		}
		if len(agent.Targets) == 0 {
			issues = append(issues, fmt.Sprintf("agent %q targets are required", agent.Name))
		}
		src, err := security.ResolveWithinRoot(packageRoot, agent.Source)
		if err != nil {
			issues = append(issues, fmt.Sprintf("agent %q: %v", agent.Name, err))
		} else {
			if !strings.EqualFold(filepath.Ext(src), ".md") {
				issues = append(issues, fmt.Sprintf("agent %q source must be a Markdown file", agent.Name))
			}
			if info, err := os.Stat(src); err != nil || info.IsDir() {
				issues = append(issues, fmt.Sprintf("agent %q source does not exist", agent.Name))
			}
		}
		for target := range agent.Targets {
			if _, ok := declared[target]; !ok {
				issues = append(issues, fmt.Sprintf("agent %q declares target %q not present in package targets", agent.Name, target))
			}
			if !isSupportedTarget(target) {
				issues = append(issues, fmt.Sprintf("agent %q uses unsupported target %q", agent.Name, target))
			}
			key := plannedTargetPath(packageRoot, projectRoot, m, target, agent.Name, true)
			if prev, ok := duplicates[key]; ok {
				issues = append(issues, fmt.Sprintf("duplicate target path %q generated by %s and agent %q", key, prev, agent.Name))
			} else if key != "" {
				duplicates[key] = fmt.Sprintf("agent %q", agent.Name)
			}
		}
	}
	for _, skill := range m.Skills {
		if skill.Name == "" {
			issues = append(issues, "skill name is required")
		}
		if len(skill.Targets) == 0 {
			issues = append(issues, fmt.Sprintf("skill %q targets are required", skill.Name))
		}
		src, err := security.ResolveWithinRoot(packageRoot, skill.Source)
		if err != nil {
			issues = append(issues, fmt.Sprintf("skill %q: %v", skill.Name, err))
		} else {
			info, statErr := os.Stat(src)
			if statErr != nil || !info.IsDir() {
				issues = append(issues, fmt.Sprintf("skill %q source must be a directory", skill.Name))
			} else if _, err := os.Stat(filepath.Join(src, "SKILL.md")); err != nil {
				issues = append(issues, fmt.Sprintf("skill %q source exists, but SKILL.md was not found", skill.Name))
			}
		}
		for target := range skill.Targets {
			if _, ok := declared[target]; !ok {
				issues = append(issues, fmt.Sprintf("skill %q declares target %q not present in package targets", skill.Name, target))
			}
			if !isSupportedTarget(target) {
				issues = append(issues, fmt.Sprintf("skill %q uses unsupported target %q", skill.Name, target))
			}
			key := plannedTargetPath(packageRoot, projectRoot, m, target, skill.Name, false)
			if prev, ok := duplicates[key]; ok {
				issues = append(issues, fmt.Sprintf("duplicate target path %q generated by %s and skill %q", key, prev, skill.Name))
			} else if key != "" {
				duplicates[key] = fmt.Sprintf("skill %q", skill.Name)
			}
		}
	}
	if len(issues) > 0 {
		sort.Strings(issues)
		return issues, fmt.Errorf("manifest validation failed")
	}
	return nil, nil
}

func plannedTargetPath(packageRoot, projectRoot string, m *Manifest, target, name string, agent bool) string {
	switch target {
	case "copilot-cli":
		if agent {
			return filepath.Join(copilotBasePath(), "agents", name+".md")
		}
		return filepath.Join(copilotBasePath(), "skills", name)
	case "claude-code":
		if agent {
			return filepath.Join(projectRoot, ".claude", "agents", name+".md")
		}
		return filepath.Join(projectRoot, ".claude", "skills", name)
	case "codex-cli":
		if agent {
			return filepath.Join(projectRoot, "AGENTS.md") + "#" + name
		}
		return filepath.Join(projectRoot, ".agents", "skills", name)
	default:
		return ""
	}
}

func isSupportedTarget(target string) bool {
	switch target {
	case "copilot-cli", "claude-code", "codex-cli":
		return true
	default:
		return false
	}
}

// copilotBasePath returns the Copilot CLI home directory, falling back to
// ~/.copilot when COPILOT_HOME is not set.
func copilotBasePath() string {
	if v := os.Getenv("COPILOT_HOME"); v != "" {
		return v
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".copilot")
}
